CREATE TABLE User_T
(id NUMERIC(11,0) NOT NULL,
CustomerName VARCHAR(40) NOT NULL,
CustomerEmail VARCHAR(80) NOT NULL,
CustomerPassword VARCHAR(20) NOT NULL,
CustomerPhoneNumber NUMERIC(11) NOT NULL,
CONSTRAINT Customer_PK PRIMARY KEY (id));

CREATE TABLE Order_T
(OrderID NUMERIC(11,0) NOT NULL,
OrderDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
OrderStatus VARCHAR(10) NOT NULL, 
CustomerID NUMERIC(11,0) NOT NULL,
CONSTRAINT OrderID_PK PRIMARY KEY(OrderID),
CONSTRAINT Order_FK1 FOREIGN KEY (CustomerID) REFERENCES User_T(id));

CREATE TABLE Category_T
(CategoryID NUMERIC(2) NOT NULL,
CategoryType VARCHAR(20) NOT NULL,
CONSTRAINT CategoryID_PK PRIMARY KEY (CategoryID));

CREATE TABLE Size_T
(SizeID NUMERIC(2) NOT NULL,
Size VARCHAR(20) NOT NULL,
CONSTRAINT SizeID_PK PRIMARY KEY (SizeID));

CREATE TABLE Product_T
(ProductID  NUMERIC(11,0) NOT NULL,
ProductDescription VARCHAR(200) NOT NULL,
ProductPrice NUMERIC(6,2) NOT NULL,
SizeID NUMERIC(2) NOT NULL,
ProductColor VARCHAR(20) NOT NULL,
ProductAvailableQuantity NUMERIC (3) NOT NULL,
ProductSKUCode VARCHAR(15) NULL,
ProductImageFileName VARCHAR(40) NULL,
CategoryID NUMERIC(2) NOT NULL,
CONSTRAINT ProductID_PK PRIMARY KEY (ProductID),
CONSTRAINT CategoryID_FK1 FOREIGN KEY (CategoryID)REFERENCES Category_T(CategoryID),
CONSTRAINT SizeID_FK2 FOREIGN KEY (SizeID)REFERENCES Size_T(SizeID));


CREATE TABLE OrderLine_T
(OrderLineID NUMERIC(11,0) NOT NULL,
ProductQuantity NUMERIC(5) NOT NULL,
ProductID  NUMERIC(11,0) NOT NULL,
OrderID NUMERIC(11,0) NOT NULL,
CONSTRAINT OrderLineID_PK PRIMARY KEY(OrderLineID),
CONSTRAINT ProductID_FK1 FOREIGN KEY (ProductID)REFERENCES Product_T(ProductID),
CONSTRAINT OrderID_FK2 FOREIGN KEY(OrderId) REFERENCES Order_T(OrderID));

CREATE TABLE BillingAddress_T
(BillingAddressID NUMERIC(11,0) NOT NULL,
CustomerStreet VARCHAR(20) NOt NULL,
CustomerCity VARCHAR(20) NOT NULL,
CustomerState CHAR(2) NOT NULL,
CustomerZipCode VARCHAR(10) NOT NULL,
CustomerID NUMERIC(11,0) NOt NULL,
CONSTRAINT BillingAddressID_PK PRIMARY KEY(BillingAddressID),
CONSTRAINT CustomerID_FK1 FOREIGN KEY (CustomerID) REFERENCES User_T(Id));

CREATE TABLE ShippingAddress_T
(ShippingAddressID NUMERIC(11,0) NOT NULL,
CustomerStreet VARCHAR(20) NOt NULL,
CustomerCity VARCHAR(20) NOT NULL,
CustomerState CHAR(2) NOT NULL,
CustomerZipCode VARCHAR(10) NOT NULL,
CustomerID NUMERIC(11,0) NOt NULL,
CONSTRAINT ShippingAddressID_PK PRIMARY KEY(ShippingAddressID),
CONSTRAINT CustomerID_FK FOREIGN KEY (CustomerID) REFERENCES User_T(Id));
